#pragma once
const int PROBLEMSIZE = 50;			// ROZMIAR PROBLEMU, DOSTOSOWAÆ DO PLIKU
const int TOURNAMENTSIZE = 2;		// ROZMIAR TURNIEJU
const int POPULATIONSIZE = 20;		// ROZMIAR POPULACJI
const int CROSSINGCHANCE = 10;		// %
const int MUTATIONCHANCE = 20;		// %
const bool BIGGERRANDOM = false;	// ZWIÊKSZA LOSOWAOŒÆ PRZEZ DODATKOWE SRAND'y, ALE WYD£U¯A CZAS KOMPILACJI